### ISSUE TITLE
Throws syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM on PHP 5.2

### ISSUE THREAD

**Issue by gaurish** [gneustaetter/XLSXReader#1]
Trying to run on PHP 5.2, generates the following error

``` php
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in xlsxreader.php on line 280
```

The offending line:

``` php
$value = $self::parseRichText($cell->is);
```

I think this error is because PHP 5.2 doesn't support $stringClassName::methodName() syntax. Wondering, Is there a workaround for this?

**Comment by gneustaetter** [comment]
Removed the $ in front of $self - that should fix it

**Comment by gaurish** [comment]
Thanks for reply. I ended up upgrading to v5.3
